name: Build

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SPACK_COLOR: always
      CCACHE_DIR: ~/.spack-ci/ccache_dir
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ~/.spack-ci
        key: ${{ runner.os }}-spack-${{ hashFiles('./tools/environments/ci/spack.yaml') }}
        restore-keys: ${{ runner.os }}-spack-
    - name: Setup Spack
      run: |
        wget -q https://github.com/haampie/spack-batteries-included/releases/download/develop/spack-x86_64.x -O ~/spack.x && chmod +x ~/spack.x
        ~/spack.x -e ./tools/environments/ci/ repo add ./tools/spack
        ~/spack.x -e ./tools/environments/ci/ concretize
    - name: Build and test
      run: |
        ~/spack.x -e ./tools/environments/ci/ install -v --test=root