name: Build

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache Spack
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.spack-ci
        key: spack
        restore-keys: spack
    - name: Setup Spack
      run: |
        echo $PATH
        wget -q https://github.com/haampie/spack-batteries-included/releases/download/develop/spack-x86_64.x -O ~/spack.x && chmod +x ~/spack.x
        ~/spack.x -e ./tools/environments/ci/ repo add ./tools/spack
        ~/spack.x -e ./tools/environments/ci/ concretize
    - name: Build and test
      run: |
        ~/spack.x -e ./tools/environments/ci/ install -v --test=root